# Generated by Django 4.2.3 on 2023-07-17 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languagesicons',
            name='icon',
            field=models.ImageField(blank=True, upload_to='language_icons/', verbose_name='Language Icon Image:(icons8.com)'),
        ),
    ]
